### ISSUE TITLE
[Nox.Cli] Pipeline - Invalid global variable value

### ISSUE THREAD

**Issue by gjorgji-grgovski-authoritypartners** [NoxOrg/Nox.Cli#113]
Nox.Cli is generating Pipeline variables that include the Service Name, but the value is wrapped in single quotes, leading to a failure in the build pipeline with the following error message:
`/pipeline/variables/global.yaml (Line: 10, Col: 27): While parsing a block mapping, did not find expected key.`

Expected Behavior
The global variable value for the Service Name should not be wrapped in single quotes, ensuring that the build pipeline can parse the value correctly.

Actual Behavior
The Service Name variable is enclosed in single quotes in the global.yaml file, causing issues during the build pipeline's parsing process.

Screenshots and Additional Information
https://dev.azure.com/iwgplc/Nox.Workplace/_build?definitionId=2470&_a=summary
![image](https://github.com/NoxOrg/Nox.Cli/assets/131167535/060a546c-632b-4e7c-ba14-cb91b57e5cfb)

**Comment by AndreyDegtyarev** [comment]
https://regusit.atlassian.net/browse/NOX-140
