### ISSUE TITLE
Wildcard variable resolution

### ISSUE THREAD

**Issue by jan-schutte** [NoxOrg/Nox.Cli#44]
Add a feature to allow for wildcard variable resolution.
Example: 
Lets say there is an environment variable named env.hostName and also a config.hostName.
Developers should be able to use *.hostName in their scripts.
Order of presidence should be discussed but could look like:
1) config
2) env
3) secret

**Comment by rochar** [comment]
@jan-schutte  will revisit this after the refactor is completed

**Comment by jan-schutte** [comment]
This is deprecated, Nox.Solution resolves variables from secrets and environments
